apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://27F7468913212D4D40ECB106E3F0AA68.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
    user: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
  name: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
current-context: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:554257238497:cluster/eksclusterdemo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - eksclusterdemo
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
