kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-name
  labels:
    app: wordpress
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql
