name: Deploy to AWS-ECR

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
       skip-logout: true

    - name: Build, tag, and PuSh image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: compose-repo
        IMAGE_TAG: latest
      run: |
        pwd
        ls
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        ls
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Pull the latest image
      run: |
          docker pull 554257238497.dkr.ecr.ap-south-1.amazonaws.com/compose-repo:latest
    - name: Configure kubectl
      run: |
          aws eks update-kubeconfig --region ap-south-1 --name eksclusterdemo
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Deploy MySQL with Helm
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm install mysql bitnami/mysql \
          --namespace wordpress \
          --create-namespace \
          --set auth.rootPassword=password \
          --set auth.database=wordpress \
          --set persistence.size=1Gi

    - name: Deploy WordPress with Helm
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm install wordpress bitnami/wordpress \
          --namespace wordpress \
          --set wordpressUsername=admin \
          --set wordpressPassword=password \
          --set wordpressEmail=admin@example.com \
          --set mariadb.enabled=false \
          --set externalDatabase.host=mysql-wordpress.wordpress.svc.cluster.local \
          --set externalDatabase.user=bn_wordpress \
          --set externalDatabase.password=bitnami \
          --set externalDatabase.database=wordpress

    - name: Verify Deployment
      run: |
        helm install wordpress bitnami
        helm list
