name: Deploy WordPress

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Adding Known Hosts
      run: |
        mkdir ~/.ssh
        ssh-keyscan -p 22 -H 13.233.0.104  >> ~/.ssh/known_hosts
    - name: SCP
      env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
          HOSTNAME : 13.233.0.104
          USER_NAME : ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        tar -czf data.tar.gz docker-compose.yml
        ls -l
        scp -o StrictHostKeyChecking=no -i private_key data.tar.gz ${USER_NAME}@${HOSTNAME}:/home/ubuntu/data.tar.gz
    - name: wordpress
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: |
          sudo apt-get update -y
          sudo apt-get install \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
          "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          sudo mv /home/ubuntu/data.tar.gz /var/www/html/
          sudo tar -xvzf /var/www/html/data.tar.gz -C /var/www/
          tar -czvf /home/ubuntu/backup_$(date +%Y-%m-%d_%H-%M-%S).tar.gz /var/www/html/
        host: 13.233.0.104
        user: ubuntu
        key: ${{ secrets.SSH_KEY}}
    
