name: Deploy WordPress

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Adding Known Hosts
      run: |
        mkdir ~/.ssh
        ssh-keyscan -p 22 -H 13.234.204.95  >> ~/.ssh/known_hosts
    - name: SCP
      env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY  }}
          HOSTNAME : 13.234.204.95
          USER_NAME : ubuntu
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ${USER_NAME}@${HOSTNAME}:/home/ubuntu/
        tar -czf data.tar.gz html/
        scp -o StrictHostKeyChecking=no -i private_key data.tar.gz ${USER_NAME}@${HOSTNAME}:/home/ubuntu/data.tar.gz
        scp -o StrictHostKeyChecking=no -i private_key Dockerfile ${USER_NAME}@${HOSTNAME}:/home/ubuntu/
    - name: wordpress
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
        command: |
          mkdir wp-dir
          sudo tar -xvzf /home/ubuntu/data.tar.gz -C /home/ubuntu/wp-dir/
          sudo mv docker-compose.yml /home/ubuntu/wp-dir/
          sudo mv Dockerfile /home/ubuntu/wp-dir/html/
          cd wp-dir/
          
          sudo tar -xvzf /home/ubuntu/data.tar.gz -C /home/ubuntu/wp-dir
          cd /home/ubuntu/wp-dir/html
          docker build --no-cache -t wp .
          docker-compose down
          docker-compose up -d
        host: 13.234.204.95
        user: ubuntu
        key: ${{ secrets.SSH_KEY}}
   
        
    
